export type IdeaStatus =
  | "SHIPPED"
  | "WEAK"
  | "MODERATE"
  | "STRONG"
  | "DEAD";
export type BuildTime = "weekend" | "week" | "complex" | "ai";
export type PricingTier = "entry" | "standard" | "premium";

export type Idea = {
  rank: number;
  name: string;
  slug: string;
  category: string;
  group: string;
  pop: number;
  diff: number;
  kwScore: number;
  compReviews: number;
  compScore: number;
  totalScore: number;
  status: IdeaStatus;
  buildTime: BuildTime;
  pricingTier: PricingTier;
  pricing: { weekly: string; monthly: string; annual: string; trial: string };
  primaryKeyword: string;
  concept: string;
  targetKeywords: string[];
  competitors: { name: string; reviews: string; rating: string }[];
  features: string[];
  implementation: string[];
  monetization: string;
  whyBuild: string;
  vidnotesPattern?: boolean;
  buildPrompt?: string;
  mergeNote?: string;
};

export const ideas: Idea[] = [
  {
    rank: 1,
    name: "Matcha Finder",
    slug: "matcha-finder",
    category: "Food & Drink",
    group: "Specialty",
    pop: 63, diff: 9, kwScore: 54, compReviews: 7, compScore: 38, totalScore: 92,
    status: "WEAK",
    buildTime: "complex",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "matcha",
    concept: "A lifestyle app for matcha enthusiasts — find nearby matcha cafes, rate matcha drinks, track your matcha journey with tasting notes. Target the booming matcha culture among health-conscious millennials and Gen Z.",
    targetKeywords: ["matcha", "matcha map", "matcha cafe", "matcha tea", "matcha finder", "green tea", "latte finder", "tea shop"],
    competitors: [
      { name: "Matcha Map – For Matcha Lovers", reviews: "7", rating: "4.4" },
      { name: "Matcha Cafe", reviews: "0", rating: "-" },
      { name: "Matcha Kari", reviews: "1", rating: "-" },
    ],
    features: ["Find nearby matcha cafes with MapKit integration", "Rate and review matcha drinks with tasting notes", "Track your matcha journey with a personal journal", "Community-submitted cafe locations via CloudKit", "Favorites sync across devices", "Beautiful curated cafe database"],
    implementation: ["MapKit", "Core Location", "CloudKit for cafe database", "User-submitted locations", "SwiftUI"],
    monetization: "Freemium — free cafe finder, premium for tasting journal, favorites sync, ad-free. $4.99/week or $24.99/year.",
    whyBuild: "Pop 63 with diff 9 = ratio 7.00 (BEST in entire dataset). Top dedicated app has only 7 reviews. #3 result is a crypto app ranking accidentally. The matcha culture is booming and completely underserved on mobile.",
  },
  {
    rank: 2,
    name: "Mini Golf Scorecard",
    slug: "mini-golf-scorecard",
    category: "Sports",
    group: "Scorer",
    pop: 44, diff: 9, kwScore: 35, compReviews: 3225, compScore: 10, totalScore: 85,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "mini golf score card",
    concept: "Clean, modern mini golf scoring app with course lookup, group scoring for up to 8 players, stats tracking, and sharing. Differentiate with Apple Watch companion, iMessage sharing, and beautiful course-themed UI.",
    targetKeywords: ["mini golf score card", "mini golf", "putt putt", "mini golf scorer", "golf scorecard"],
    competitors: [
      { name: "Mini-Golf Score Card", reviews: "3,225", rating: "4.8" },
      { name: "Mini Golf Scoring Card", reviews: "19", rating: "4.7" },
      { name: "Putts - Mini-Golf Score Card", reviews: "4", rating: "-" },
      { name: "Golf & Mini-Golf Scorecard", reviews: "71", rating: "4.7" },
    ],
    features: ["Group scoring for up to 8 players", "Course lookup database", "Stats tracking and history", "Apple Watch companion", "iMessage sharing", "Beautiful course-themed UI"],
    implementation: ["SwiftUI", "SwiftData", "WatchKit", "ShareLink"],
    monetization: "Freemium — free basic scoring, premium for stats/history/watch. $4.99/week or $24.99/year.",
    whyBuild: "Pop 44 with diff 9 = ratio 4.89. #1 has 3,225 reviews BUT diff is only 9 which means ranking is achievable. Many small competitors prove the market. Apple Watch companion is the killer differentiator.",
  },
  {
    rank: 3,
    name: "ID Scanner Pro",
    slug: "id-scanner-pro",
    category: "Business",
    group: "Utility",
    pop: 53, diff: 15, kwScore: 38, compReviews: 3024, compScore: 10, totalScore: 83,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "id scanner",
    concept: "Scan IDs, passports, and driver's licenses using the camera. Extract name, DOB, expiry, address via OCR. Target small business owners for age verification, plus individuals who need to save ID info digitally.",
    targetKeywords: ["id scanner", "passport scanner", "document scanner", "license scanner", "ocr scanner", "barcode scanner"],
    competitors: [
      { name: "ID Scanner Professional", reviews: "3,024", rating: "4.6" },
      { name: "ID Scanner", reviews: "787", rating: "4.3" },
      { name: "Vemos - ID Scan", reviews: "137", rating: "3.6" },
      { name: "Scannr (ID check)", reviews: "566", rating: "4.0" },
    ],
    features: ["Camera-based ID scanning with OCR text extraction", "Support for passports, driver's licenses, and ID cards", "PDF417 barcode reading", "Save scanned ID info digitally", "Age verification mode for businesses", "Export and share scan results"],
    implementation: ["Vision framework (VNRecognizeTextRequest)", "VNDetectBarcodesRequest for PDF417", "SwiftUI", "Camera capture"],
    monetization: "Hard paywall — scan limit on free, unlimited on premium. $7.99/week or $49.99/year.",
    whyBuild: "Pop 53 with diff 15 = ratio 3.53. Crowded B2B market but diff 15 means ranking is very achievable. Top apps target bars/clubs — room for a general-purpose personal scanner. Simpler and cheaper than B2B competitors.",
  },
  {
    rank: 4,
    name: "Deep Conversation Cards",
    slug: "deep-conversation-cards",
    category: "Entertainment",
    group: "Content",
    pop: 44, diff: 13, kwScore: 31, compReviews: 1955, compScore: 10, totalScore: 80,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "deep conversations",
    concept: "Beautifully designed conversation card decks for couples, friends, families, and coworkers. Swipe through themed question packs — Deep & Meaningful, Spicy Couples, Family Dinner, Team Building.",
    targetKeywords: ["deep conversations", "conversation starters", "couples questions", "icebreaker", "talk cards", "relationship questions"],
    competitors: [
      { name: "HH Talk - Deep Conversations", reviews: "1,955", rating: "4.7" },
      { name: "Deep Conversations", reviews: "14", rating: "4.7" },
      { name: "Conversation starters: DTalk", reviews: "19", rating: "4.3" },
      { name: "Couples Questions Velvet Talks", reviews: "88", rating: "4.9" },
      { name: "Lets Get Deep", reviews: "378", rating: "4.7" },
    ],
    features: ["Themed question card packs (20+ decks)", "Swipe-based card interface", "Categories: couples, friends, family, coworkers", "Haptic feedback on card interactions", "Favorites and history", "Share individual cards"],
    implementation: ["SwiftUI", "SwiftData", "JSON content packs", "Haptics"],
    monetization: "Freemium — 1 free deck, premium unlocks all 20+ decks. $4.99/week or $24.99/year.",
    whyBuild: "Pop 44 with diff 13 = ratio 3.38. HH Talk dominates but many small apps coexist. Content app = easy to differentiate with better card packs. Merges 'deep conversations' + 'conversation starters' keywords.",
  },
  {
    rank: 5,
    name: "Hymn Book",
    slug: "hymn-book",
    category: "Books",
    group: "Content",
    pop: 27, diff: 9, kwScore: 18, compReviews: 143, compScore: 25, totalScore: 78,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "hymn book",
    concept: "Digital hymn book with 1,000+ classic hymns, search by title/lyrics/number, audio playback, favorites, offline mode. Target church-goers, worship leaders, choir members. Include multiple hymnals.",
    targetKeywords: ["hymn book", "hymns", "christian hymns", "gospel songs", "church songs", "worship music", "choir songs"],
    competitors: [
      { name: "Gospel Hymns and Songs GHS", reviews: "4", rating: "4.5" },
      { name: "Gospel Hymn Book + Audio", reviews: "143", rating: "4.2" },
      { name: "Iwe Orin Mimo", reviews: "8", rating: "3.1" },
      { name: "The Christian Hymn Book", reviews: "2", rating: "-" },
    ],
    features: ["1,000+ classic hymns searchable by title, lyrics, or number", "Audio playback for each hymn", "Favorites and offline mode", "Multiple hymnals (Baptist, Methodist, Catholic)", "Full-text search across all lyrics", "Adjustable font size for readability"],
    implementation: ["SwiftUI", "Full-text search", "AVFoundation for audio", "Offline content bundle"],
    monetization: "Freemium — 100 free hymns, premium for full library + audio. $4.99/week or $24.99/year.",
    whyBuild: "Pop 27 with diff 9 = ratio 3.00. Diff 9 is incredibly low. Top dedicated apps are small. The largest (143 reviews) has only 4.2 rating. Easy win with loyal, paying religious audience.",
  },
  {
    rank: 6,
    name: "Chess Clock",
    slug: "chess-clock",
    category: "Board",
    group: "Timer",
    pop: 47, diff: 17, kwScore: 30, compReviews: 334, compScore: 20, totalScore: 77,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "chess clock",
    concept: "Beautiful chess clock with Fischer, Bronstein, and increment time controls. Minimalist design with haptic feedback, customizable colors, sound effects. Also works as a general game timer for board games.",
    targetKeywords: ["chess clock", "chess timer", "game timer", "board game timer", "blitz timer", "tournament clock"],
    competitors: [
      { name: "Chess Clock by Chess.com", reviews: "334", rating: "4.6" },
      { name: "ChessClock+", reviews: "102", rating: "4.9" },
      { name: "Chess Clock - Speed Timer", reviews: "41", rating: "4.4" },
    ],
    features: ["Fischer, Bronstein, and increment time controls", "Minimalist design with haptic feedback", "Customizable colors and sound effects", "Apple Watch companion", "Works as general board game timer", "Custom preset management"],
    implementation: ["SwiftUI", "Haptics", "WatchKit", "Custom timer engine"],
    monetization: "Freemium — basic timer free, premium for custom presets, themes, watch app. $7.99/week or $49.99/year.",
    whyBuild: "Pop 47 with diff 17 = ratio 2.76. Chess.com has brand advantage but only 334 reviews on their clock app. Diff 17 is very achievable. Apple Watch companion is the differentiator.",
  },
  {
    rank: 7,
    name: "Token Board",
    slug: "token-board",
    category: "Education",
    group: "Specialty",
    pop: 24, diff: 9, kwScore: 15, compReviews: 2114, compScore: 10, totalScore: 72,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "token board",
    concept: "Digital token board for ABA therapy, special needs classrooms, and positive behavior reinforcement. Customizable token images, sound effects on completion, data tracking for therapists/parents.",
    targetKeywords: ["token board", "reward chart", "behavior chart", "aba therapy", "autism app", "reinforcement"],
    competitors: [
      { name: "Token Board GO", reviews: "2,114", rating: "4.6" },
      { name: "My Token Board", reviews: "9", rating: "3.2" },
      { name: "ABA Token Board", reviews: "9", rating: "4.9" },
      { name: "Token Board ABA", reviews: "2", rating: "-" },
    ],
    features: ["Customizable token images and sounds", "Sound effects on completion", "Data tracking for therapists and parents", "Simple enough for a child to use", "Unlimited boards with custom tokens", "Data export for therapy reports"],
    implementation: ["SwiftUI", "SwiftData", "Drag-and-drop", "Haptics", "Sound effects"],
    monetization: "Freemium — 1 free board, premium for unlimited boards, data export, custom tokens. $4.99/week or $24.99/year.",
    whyBuild: "Pop 24 with diff 9 = ratio 2.67. Token Board GO dominates with 2,114 reviews BUT diff 9 means ranking is very easy. ABA therapy parents are high-paying and loyal users.",
  },
  {
    rank: 8,
    name: "Bowling Scorekeeper",
    slug: "bowling-scorekeeper",
    category: "Sports",
    group: "Scorer",
    pop: 48, diff: 19, kwScore: 29, compReviews: 2115, compScore: 10, totalScore: 72,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "bowling score keeper",
    concept: "Track bowling scores with proper frame-by-frame scoring, strikes/spares detection, and stat analytics. Multi-player support for league nights. Track averages, high scores, and improvement over time.",
    targetKeywords: ["bowling score keeper", "bowling calculator", "bowling app", "bowling tracker", "bowling stats", "league bowling"],
    competitors: [
      { name: "BowlingScore - Easy Record", reviews: "57", rating: "4.6" },
      { name: "Bosc: Bowling Score Keeper App", reviews: "358", rating: "4.8" },
      { name: "Bowling Calculator", reviews: "44", rating: "3.6" },
      { name: "Best Bowling LT", reviews: "152", rating: "4.5" },
      { name: "Lanetalk Bowling", reviews: "2,115", rating: "3.8" },
    ],
    features: ["Frame-by-frame scoring with strikes/spares", "Multi-player support for league nights", "Stat analytics and improvement tracking", "Average and high score history", "Charts framework for visualizations", "Export game data"],
    implementation: ["SwiftUI", "SwiftData", "Bowling scoring algorithm", "Charts framework"],
    monetization: "Freemium — free basic scoring, premium for stats/history/export. $7.99/week or $49.99/year.",
    whyBuild: "Pop 48 with diff 19 = ratio 2.53. Several competitors but most have mediocre ratings. Bowling is evergreen. Diff 19 with pop 48 is a great ratio.",
  },
  {
    rank: 9,
    name: "Haiku Writer",
    slug: "haiku-writer",
    category: "Entertainment",
    group: "Content",
    pop: 52, diff: 21, kwScore: 31, compReviews: 948, compScore: 15, totalScore: 70,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "haiku",
    concept: "AI-powered haiku writing assistant. Type a theme or take a photo, get a beautiful haiku. Save to a personal journal, share as images on social media. Include syllable counter, seasonal word suggestions, and daily prompts.",
    targetKeywords: ["haiku", "poetry", "poem writer", "syllable counter", "japanese poetry", "creative writing"],
    competitors: [
      { name: "Epic Haiku & Limerick", reviews: "948", rating: "2.5" },
      { name: "Haiku - Poems made simple", reviews: "55", rating: "4.2" },
      { name: "Haiku by BAF (Retired)", reviews: "1,672", rating: "-" },
    ],
    features: ["AI-powered haiku generation from themes or photos", "Personal haiku journal", "Share as beautiful images on social media", "Syllable counter", "Seasonal word suggestions (kigo)", "Daily haiku prompts"],
    implementation: ["OpenAI/Claude API for haiku generation", "SwiftUI", "Image export", "ShareLink"],
    monetization: "Freemium — 3 free haiku/day, premium for unlimited + AI themes. $7.99/week or $49.99/year.",
    whyBuild: "Pop 52 with diff 21 = ratio 2.48. Top dedicated app has 2.5 rating (TERRIBLE). #4 is retired. Only 1 real competitor at 55 reviews. Wide open market.",
  },
  {
    rank: 10,
    name: "PSAT Score Calculator",
    slug: "psat-score-calculator",
    category: "Education",
    group: "Calculator",
    pop: 52, diff: 21, kwScore: 31, compReviews: 0, compScore: 40, totalScore: 71,
    status: "WEAK",
    buildTime: "weekend",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "none" },
    primaryKeyword: "psat score",
    concept: "Enter your raw PSAT scores, get your predicted National Merit Scholarship qualifying score. Include score conversion tables, percentile rankings, college readiness benchmarks, and historical cutoff scores by state.",
    targetKeywords: ["psat score", "psat", "sat prep", "national merit", "psat calculator", "psat results"],
    competitors: [
      { name: "PSAT Test Prep 2026", reviews: "39", rating: "4.6" },
      { name: "PSAT Practice Exam 2026", reviews: "10", rating: "3.9" },
      { name: "PSAT Score Calculator", reviews: "0", rating: "-" },
    ],
    features: ["Raw-to-scaled score conversion", "SAT score range prediction", "National Merit cutoff by state", "Section-by-section breakdown", "Historical score comparison", "Shareable score card"],
    implementation: ["SwiftUI", "Score conversion tables", "SAT prediction algorithm", "National Merit cutoff by state", "No backend needed"],
    monetization: "Hard paywall — basic calc free, detailed analysis premium. $7.99/week or $49.99/year. No trial (impulse buy).",
    whyBuild: "Pop 52 with diff 21 = ratio 2.48. Nobody has built a good PSAT score calculator. Prep apps exist but not score conversion tools. 3.7 million students take the PSAT every October. Massive seasonal spike.",
  },
  {
    rank: 11,
    name: "Peptide Calculator",
    slug: "peptide-calculator",
    category: "Health & Fitness",
    group: "Calculator",
    pop: 52, diff: 21, kwScore: 31, compReviews: 431, compScore: 15, totalScore: 68,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "peptide calculator",
    concept: "Peptide reconstitution and dosage calculator for GLP-1, BPC-157, and other peptides. Enter vial size, bacteriostatic water volume, desired dose — get exact units to draw. Include injection site rotation tracker.",
    targetKeywords: ["peptide calculator", "reconstitution calculator", "glp-1", "ozempic", "bpc-157", "dosage calculator"],
    competitors: [
      { name: "Peptides Calculator", reviews: "135", rating: "4.3" },
      { name: "Peptide Calculator: PepCalc", reviews: "187", rating: "4.6" },
      { name: "Peptide Calculator App", reviews: "431", rating: "4.4" },
      { name: "Peptide Calculator PRO", reviews: "129", rating: "4.7" },
    ],
    features: ["Reconstitution calculator for any peptide", "Dosage calculation with syringe units", "Injection site rotation tracker", "Dose logging and history", "Support for GLP-1, BPC-157, and more", "Quick reference drug database"],
    implementation: ["SwiftUI", "Dosage algorithms", "SwiftData for logging"],
    monetization: "Hard paywall — 1 free calc, premium for all peptides + logging. $7.99/week or $49.99/year.",
    whyBuild: "Pop 52 with diff 21 = ratio 2.48. Many dedicated competitors but the niche is BOOMING (GLP-1/Ozempic trend). Diff 21 is manageable. High willingness to pay in health niche.",
  },
  {
    rank: 12,
    name: "Deck of Cards",
    slug: "deck-of-cards",
    category: "Entertainment",
    group: "Interactive Fun",
    pop: 32, diff: 13, kwScore: 19, compReviews: 835, compScore: 15, totalScore: 68,
    status: "WEAK",
    buildTime: "weekend",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "none" },
    primaryKeyword: "deck of cards",
    concept: "Virtual deck of playing cards — shuffle, draw, deal for any card game. Support multiple deck types (standard, tarot, UNO-style). Add drinking game presets and custom card creation.",
    targetKeywords: ["deck of cards", "playing cards", "card deck", "virtual cards", "card game", "shuffle cards"],
    competitors: [
      { name: "Draw a Card Deck", reviews: "835", rating: "4.6" },
      { name: "Deck of Cards - Virtual deal", reviews: "4", rating: "2.8" },
      { name: "iDeckOfCards", reviews: "355", rating: "4.1" },
    ],
    features: ["Shuffle, draw, and deal cards", "Multiple deck types (standard, tarot, UNO-style)", "Drinking game presets", "Custom card creation", "Realistic card animations", "Haptic feedback"],
    implementation: ["SwiftUI", "Card animations", "Shuffle algorithm", "Haptics"],
    monetization: "Freemium — standard deck free, premium for custom decks, themes, games. $4.99/week or $24.99/year.",
    whyBuild: "Pop 32 with diff 13 = ratio 2.46. Simple concept with clear demand. Weekend build with high upside.",
  },
  {
    rank: 13,
    name: "Pill Counter AI",
    slug: "pill-counter-ai",
    category: "Medical",
    group: "AI Camera",
    pop: 36, diff: 15, kwScore: 21, compReviews: 547, compScore: 15, totalScore: 67,
    status: "MODERATE",
    buildTime: "complex",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "pill counter",
    concept: "Point your camera at pills, count them automatically using computer vision. Use cases: pharmacy inventory, medication compliance, caregiver pill tracking. Also identify pills by shape/color/imprint.",
    targetKeywords: ["pill counter", "pill identifier", "medication counter", "pharmacy counter", "pill scan", "medicine counter"],
    competitors: [
      { name: "PillEye – tablet, pill counter", reviews: "216", rating: "2.9" },
      { name: "iCyclop", reviews: "432", rating: "4.8" },
      { name: "pillphill - pill counter", reviews: "547", rating: "4.4" },
    ],
    features: ["Camera-based automatic pill counting", "Pill identification by shape/color/imprint", "Pharmacy inventory mode", "Medication compliance tracking", "Merge pill counter + pill identifier keywords", "Export count reports"],
    implementation: ["Vision framework (object detection)", "Core ML", "Camera real-time processing"],
    monetization: "Hard paywall — 5 free counts, premium unlimited. $7.99/week or $49.99/year.",
    whyBuild: "Pop 36 with diff 15 = ratio 2.40. Leader has 2.9 rating (opportunity!). B2B pharmacy market pays well. Merges pill counter + pill identifier for double keyword coverage.",
  },
  {
    rank: 14,
    name: "Check Writer",
    slug: "check-writer",
    category: "Finance",
    group: "Utility",
    pop: 26, diff: 11, kwScore: 15, compReviews: 304, compScore: 20, totalScore: 67,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "check writer",
    concept: "Write and print personal checks from your phone. Enter payee, amount, date — app fills the check template, prints on check stock via AirPrint. Auto-converts amounts to words.",
    targetKeywords: ["check writer", "print checks", "check printing", "cheque writer", "check template", "bank check"],
    competitors: [
      { name: "Check Writer: Print Checks", reviews: "304", rating: "4.2" },
      { name: "Check Writer - Write & Print", reviews: "71", rating: "4.6" },
      { name: "Online Check Writer", reviews: "42", rating: "2.7" },
      { name: "Smart Cheque Writer", reviews: "34", rating: "4.4" },
    ],
    features: ["Fill and print personal checks via AirPrint", "Auto-convert amounts to words", "Check register tracking", "Cleared check tracking", "PDF generation", "Multiple check templates"],
    implementation: ["SwiftUI", "AirPrint (UIPrintInteractionController)", "PDF generation", "Number-to-words conversion"],
    monetization: "Hard paywall — 1 free check, premium for unlimited. $4.99/week or $24.99/year.",
    whyBuild: "Pop 26 with diff 11 = ratio 2.36. Top app has only 304 reviews at 4.2. Users clearly willing to pay for check writing tools.",
  },
  {
    rank: 15,
    name: "Bingo Caller",
    slug: "bingo-caller",
    category: "Entertainment",
    group: "Interactive Fun",
    pop: 35, diff: 15, kwScore: 20, compReviews: 70, compScore: 30, totalScore: 67,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "bingo caller",
    concept: "Turn your phone into a bingo caller machine. Random ball drawing with voice announcements, customizable speed, ball display board, and card generator. Perfect for family game nights, church events, and senior centers.",
    targetKeywords: ["bingo caller", "bingo", "bingo generator", "bingo at home", "bingo machine", "bingo game"],
    competitors: [
      { name: "Bingo Caller", reviews: "70", rating: "4.2" },
      { name: "Bingo at Home", reviews: "378", rating: "3.2" },
      { name: "Bingo Call", reviews: "90", rating: "2.8" },
      { name: "Bingo Caller at Home", reviews: "142", rating: "4.6" },
    ],
    features: ["Random ball drawing with voice announcements", "Customizable draw speed", "Ball display board", "Card generator for printing", "75-ball and 90-ball modes", "Custom game modes"],
    implementation: ["SwiftUI", "AVSpeechSynthesizer", "Random number engine", "PDF card generation"],
    monetization: "Freemium — basic 75-ball free, premium for custom games, card printing. $7.99/week or $49.99/year.",
    whyBuild: "Pop 35 with diff 15 = ratio 2.33. Top caller has only 70 reviews at 4.2 rating. #2 and #3 have bad ratings. Clear opportunity for a polished caller app.",
  },
  {
    rank: 16,
    name: "Game Sheet",
    slug: "game-sheet",
    category: "Sports",
    group: "Scorer",
    pop: 25, diff: 11, kwScore: 14, compReviews: 11, compScore: 35, totalScore: 66,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "gamesheet",
    concept: "Universal digital score sheet for any sport or game. Pre-built templates for hockey, soccer, basketball, plus custom scoring. Track stats per player, period scores, penalties. Export game reports as PDF.",
    targetKeywords: ["gamesheet", "score sheet", "game scorer", "sports scorecard", "hockey score", "soccer score"],
    competitors: [
      { name: "GameSheet Teams", reviews: "6", rating: "3.7" },
      { name: "GameSheet Soccer Scoring", reviews: "1", rating: "-" },
      { name: "RAMP GameSheets", reviews: "11", rating: "4.4" },
      { name: "Game Sheet", reviews: "1", rating: "5.0" },
    ],
    features: ["Pre-built templates for hockey, soccer, basketball", "Custom scoring templates", "Per-player stat tracking", "Period scores and penalties", "PDF game report export", "Universal game scoring"],
    implementation: ["SwiftUI", "SwiftData", "PDF export", "Template engine"],
    monetization: "Freemium — 3 free templates, premium for all sports + custom + export. $4.99/week or $24.99/year.",
    whyBuild: "Pop 25 with diff 11 = ratio 2.27. No app has more than 11 reviews. Wide open niche for a universal game scoring app.",
  },
  {
    rank: 17,
    name: "Floating Apps",
    slug: "floating-apps",
    category: "Productivity",
    group: "Utility",
    pop: 43, diff: 19, kwScore: 24, compReviews: 846, compScore: 15, totalScore: 65,
    status: "MODERATE",
    buildTime: "complex",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "floating apps",
    concept: "Float mini apps over other apps using Picture-in-Picture. Clock, calculator, notes, timer, translator all available as floating windows. Productivity multitasking that iOS doesn't natively support well.",
    targetKeywords: ["floating apps", "pip", "split screen", "floating window", "overlay app", "multitask"],
    competitors: [
      { name: "Split Screen - Floating Apps", reviews: "846", rating: "4.5" },
      { name: "Twins: Split Screen Dual View", reviews: "176", rating: "4.3" },
      { name: "Floating Clock - Teleprompter", reviews: "78", rating: "4.1" },
    ],
    features: ["Float mini apps using Picture-in-Picture", "Clock, calculator, notes, timer widgets", "Translator floating window", "Works over any app", "Customizable floating widget size", "Quick launch from shortcut"],
    implementation: ["AVPictureInPictureController", "Custom PiP content", "SwiftUI"],
    monetization: "Freemium — 1 floating widget free, premium for all widgets. $7.99/week or $49.99/year.",
    whyBuild: "Pop 43 with diff 19 = ratio 2.26. Top app has 846 reviews. iOS limits what's possible but PiP-based floating works. High pop keyword.",
  },
  {
    rank: 18,
    name: "Shot Timer",
    slug: "shot-timer",
    category: "Sports",
    group: "Timer",
    pop: 29, diff: 13, kwScore: 16, compReviews: 946, compScore: 15, totalScore: 65,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "shot timer",
    concept: "Precision shot timer for firearms training. Detect shots via microphone, display split times, record strings. Include par time mode, random start delay, and drill templates.",
    targetKeywords: ["shot timer", "par timer", "range timer", "firearms training", "shooting timer", "gun timer"],
    competitors: [
      { name: "ShootOnTime: Par Timer", reviews: "946", rating: "4.9" },
      { name: "Range Timer AP", reviews: "11", rating: "3.3" },
      { name: "Par Timer Pro: Firearm Trainer", reviews: "341", rating: "4.6" },
      { name: "Gun Shot Timer", reviews: "197", rating: "2.0" },
    ],
    features: ["Shot detection via microphone", "Split time display", "Par time mode with random start delay", "Drill templates", "String recording and history", "Export session data"],
    implementation: ["AVAudioEngine for shot detection", "High-precision timing", "SwiftUI"],
    monetization: "Hard paywall — basic timer free, premium for drills, history, export. $7.99/week or $49.99/year.",
    whyBuild: "Pop 29 with diff 13 = ratio 2.23. Firearms community always wants alternatives. #4 has terrible rating (2.0). Firearms users pay premium prices.",
  },
  {
    rank: 19,
    name: "Hunting Calls",
    slug: "hunting-calls",
    category: "Sports",
    group: "Specialty",
    pop: 23, diff: 11, kwScore: 12, compReviews: 118, compScore: 25, totalScore: 65,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "coyote calls",
    concept: "All-in-one hunting calls app: coyote, predator, turkey, elk, duck, deer. High-quality audio recordings, timer between calls, GPS location marking. Combine what competitors split across multiple apps.",
    targetKeywords: ["coyote calls", "hunting calls", "predator calls", "turkey calls", "elk calls", "duck calls"],
    competitors: [
      { name: "Hunting Calls: Coyote", reviews: "118", rating: "4.6" },
      { name: "Hunting Calls: Rabbit & Hare", reviews: "61", rating: "4.7" },
      { name: "Coyote and Predator Calls", reviews: "35", rating: "4.1" },
      { name: "Coyote & Predator Hunting Calls", reviews: "69", rating: "2.6" },
    ],
    features: ["All-in-one: coyote, turkey, elk, duck, deer calls", "High-quality audio recordings", "Timer between calls", "GPS location marking", "Combine species that competitors split across apps", "Offline audio playback"],
    implementation: ["AVFoundation", "Bundled audio files", "MapKit for location pins", "Timer"],
    monetization: "Freemium — coyote calls free, premium for all species. $7.99/week or $49.99/year.",
    whyBuild: "Pop 23 with diff 11 = ratio 2.09. One developer owns this niche with separate per-species apps. A unified hunting calls app could win. Diff 11 is very low.",
  },
  {
    rank: 20,
    name: "Watch Me Grow",
    slug: "watch-me-grow",
    category: "Lifestyle",
    group: "Specialty",
    pop: 34, diff: 17, kwScore: 17, compReviews: 71, compScore: 30, totalScore: 64,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "watch me grow",
    concept: "Track your baby's growth milestones — height, weight, head circumference plotted on WHO growth curves. Monthly photo diary with size comparison objects. Share milestone cards on social media.",
    targetKeywords: ["watch me grow", "baby growth", "baby tracker", "growth chart", "baby milestones", "infant tracker"],
    competitors: [
      { name: "WatchMeGrow", reviews: "71", rating: "2.1" },
    ],
    features: ["Height, weight, head circumference tracking", "WHO growth curve plotting", "Monthly photo diary with size comparisons", "Shareable milestone cards", "Well-baby checkup reminders", "Export growth data"],
    implementation: ["SwiftUI", "Charts framework", "WHO growth data", "PhotosUI", "SwiftData"],
    monetization: "Freemium — basic tracking free, premium for growth charts, photo diary, export. $7.99/week or $49.99/year.",
    whyBuild: "Pop 34 with diff 17 = ratio 2.00. The one dedicated app has a 2.1 rating with only 71 reviews. Massive opportunity — terrible incumbent.",
  },
  {
    rank: 21,
    name: "Animal Scat Identifier",
    slug: "animal-scat-identifier",
    category: "Education",
    group: "AI Camera",
    pop: 25, diff: 13, kwScore: 12, compReviews: 413, compScore: 15, totalScore: 63,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "animal scat identifier",
    concept: "Point your camera at animal droppings to identify the species. Uses AI image recognition. Includes field guide with photos, animal range maps, and safety warnings. Great for hikers, hunters, nature enthusiasts.",
    targetKeywords: ["animal scat identifier", "droppings identifier", "wildlife tracker", "poop identifier", "nature guide"],
    competitors: [
      { name: "Droppings Identifier", reviews: "90", rating: "4.8" },
      { name: "Animal Scat Identifier", reviews: "413", rating: "3.9" },
      { name: "Animal Scat Identifier Poop ID", reviews: "37", rating: "4.4" },
    ],
    features: ["Camera-based scat identification", "AI image recognition", "Field guide with photos", "Animal range maps", "Safety warnings (bear scat = leave area)", "Offline field guide"],
    implementation: ["Vision framework", "Core ML or Claude Vision API", "Camera", "Offline field guide"],
    monetization: "Hard paywall — 3 free IDs, premium unlimited. $4.99/week or $24.99/year.",
    whyBuild: "Pop 25 with diff 13 = ratio 1.92. #2 has 413 reviews at 3.9 rating. Diff 13 is very low. Quirky niche with passionate outdoor enthusiasts.",
  },
  {
    rank: 22,
    name: "Birthday Candles",
    slug: "birthday-candles",
    category: "Entertainment",
    group: "Interactive Fun",
    pop: 27, diff: 15, kwScore: 12, compReviews: 1672, compScore: 10, totalScore: 62,
    status: "WEAK",
    buildTime: "weekend",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "none" },
    primaryKeyword: "birthday candle app",
    concept: "Digital birthday candles you blow out using the microphone. Set your age, blow to extinguish the flame with realistic physics. Fun for when you don't have a real cake. Add AR mode to place candles on a real surface.",
    targetKeywords: ["birthday candle app", "birthday cake", "blow out candles", "birthday party", "virtual candles"],
    competitors: [
      { name: "e-Candle", reviews: "9", rating: "5.0" },
      { name: "Candle - Happy Birthday", reviews: "2", rating: "1.0" },
      { name: "Birthday Cake-Blow out Candles", reviews: "1,672", rating: "4.6" },
    ],
    features: ["Blow out candles using microphone", "Realistic flame physics", "Set your age for correct candle count", "AR mode to place candles on surfaces", "Themed candle styles", "Birthday song playback"],
    implementation: ["SwiftUI", "SpriteKit for flame animation", "AVAudioEngine for blow detection", "ARKit optional"],
    monetization: "Freemium — basic candles free, premium for themes/effects/AR. $4.99/week or $24.99/year.",
    whyBuild: "Pop 27 with diff 15 = ratio 1.80. Only e-Candle (9 reviews) specifically targets this keyword. Simple weekend build with clear seasonal demand.",
  },
  {
    rank: 23,
    name: "QSR Inventory Counter",
    slug: "qsr-inventory-counter",
    category: "Business",
    group: "Specialty",
    pop: 27, diff: 15, kwScore: 12, compReviews: 94, compScore: 25, totalScore: 62,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "qsr inventory",
    concept: "Simple inventory counting app for quick-service restaurants. Scan items, count stock, export inventory sheets. No enterprise subscription required — works standalone. Target independent restaurant owners.",
    targetKeywords: ["qsr inventory", "inventory counter", "restaurant inventory", "stock counter", "food inventory"],
    competitors: [
      { name: "QSR Inventory (QSRSoft)", reviews: "82", rating: "3.8" },
      { name: "MyQSRSoft", reviews: "94", rating: "3.6" },
      { name: "QSROnline Counting", reviews: "13", rating: "4.5" },
    ],
    features: ["Simple inventory counting interface", "Barcode scanning", "CSV/PDF export", "Works standalone without enterprise account", "Category management", "Count history and comparisons"],
    implementation: ["SwiftUI", "Barcode scanning", "CSV/PDF export", "SwiftData"],
    monetization: "Hard paywall. $7.99/week or $49.99/year.",
    whyBuild: "Pop 27 with diff 15 = ratio 1.80. Existing apps are enterprise-tied. Room for an indie restaurant inventory counter that works standalone.",
  },
  {
    rank: 24,
    name: "Trombone Trainer",
    slug: "trombone-trainer",
    category: "Music",
    group: "Specialty",
    pop: 26, diff: 15, kwScore: 11, compReviews: 18, compScore: 30, totalScore: 61,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "trombone",
    concept: "Virtual trombone simulator with realistic slide positions and sound. Include tuner, fingering/position chart, practice exercises, and play-along mode. Target trombone students and hobbyists.",
    targetKeywords: ["trombone", "trombone simulator", "brass instrument", "trombone tuner", "music practice"],
    competitors: [
      { name: "Simple Trombone", reviews: "3", rating: "5.0" },
      { name: "Trombone Sim", reviews: "18", rating: "3.3" },
      { name: "Virtual Trumpet & Trombone", reviews: "9", rating: "3.7" },
    ],
    features: ["Virtual trombone with realistic slide positions", "Built-in tuner", "Position chart reference", "Practice exercises", "Play-along mode", "Sound synthesis"],
    implementation: ["AVFoundation", "AudioKit for sound synthesis", "Gesture recognition for slide"],
    monetization: "Freemium — basic play free, premium for lessons/tuner/exercises. $7.99/week or $49.99/year.",
    whyBuild: "Pop 26 with diff 15 = ratio 1.73. Top app has only 3 reviews. Entire niche is underserved. Music instrument apps have loyal, paying users.",
  },
  {
    rank: 25,
    name: "Heat Index Calculator",
    slug: "heat-index-calculator",
    category: "Weather",
    group: "Calculator",
    pop: 28, diff: 17, kwScore: 11, compReviews: 1600, compScore: 10, totalScore: 60,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "heat index",
    concept: "Instant heat index calculation from temperature and humidity. Show risk levels, work-rest schedules per OSHA guidelines, and real-time weather integration. Target outdoor workers, coaches, and event planners.",
    targetKeywords: ["heat index", "heat safety", "osha heat", "wet bulb temperature", "heat stress", "weather safety"],
    competitors: [
      { name: "OSHA-NIOSH Heat Safety Tool", reviews: "294", rating: "2.5" },
      { name: "Heat Safety", reviews: "1,600", rating: "4.6" },
      { name: "Heat Index: NIOSH Calculator", reviews: "0", rating: "-" },
    ],
    features: ["Instant heat index calculation", "Color-coded risk levels", "OSHA work-rest schedules", "Real-time weather integration", "Push notifications for danger thresholds", "Historical heat data charts"],
    implementation: ["SwiftUI", "WeatherKit", "Heat index formula", "Notifications"],
    monetization: "Freemium — basic calc free, premium for weather integration, alerts, history. $7.99/week or $49.99/year.",
    whyBuild: "Pop 28 with diff 17 = ratio 1.65. OSHA app has terrible 2.5 rating. Heat Safety has 1,600 reviews but room for a simpler, faster tool. Climate change driving demand.",
  },
  {
    rank: 26,
    name: "Coin Flip",
    slug: "coin-flip",
    category: "Utilities",
    group: "Interactive Fun",
    pop: 38, diff: 23, kwScore: 15, compReviews: 2894, compScore: 10, totalScore: 60,
    status: "MODERATE",
    buildTime: "weekend",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "coin flip",
    concept: "The most beautiful coin flip app ever. Realistic 3D coin physics, custom coins (US quarter, Euro, Bitcoin, etc.), streak tracking, statistics. Add dice roller and spinner wheel for the ultimate decision toolkit.",
    targetKeywords: ["coin flip", "coin toss", "heads or tails", "decision maker", "random picker", "dice roller"],
    competitors: [
      { name: "Flip a Coin App", reviews: "2,894", rating: "4.6" },
      { name: "Coin Flipper Lite", reviews: "15", rating: "3.4" },
      { name: "Coin Flip 3D - Toss It!", reviews: "147", rating: "4.6" },
    ],
    features: ["Realistic 3D coin physics", "Custom coins (US quarter, Euro, Bitcoin)", "Streak tracking and statistics", "Dice roller", "Spinner wheel", "Haptic feedback"],
    implementation: ["SwiftUI", "SceneKit for 3D coin", "Physics engine", "Haptics"],
    monetization: "Freemium — basic flip free, premium for custom coins, dice, spinner, stats. $7.99/week or $49.99/year.",
    whyBuild: "Pop 38 with diff 23 = ratio 1.65. Flip a Coin App dominates with 2,894 reviews. But the concept is SO simple that a beautiful 3D animated version could coexist.",
  },
  {
    rank: 27,
    name: "Signature Maker",
    slug: "signature-maker",
    category: "Productivity",
    group: "Utility",
    pop: 24, diff: 15, kwScore: 9, compReviews: 50, compScore: 25, totalScore: 59,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "signature generator",
    concept: "Generate professional-looking handwritten signatures from your name. Choose from multiple styles (cursive, calligraphy, modern), customize thickness and color, export as transparent PNG.",
    targetKeywords: ["signature generator", "signature maker", "digital signature", "sign maker", "autograph creator"],
    competitors: [
      { name: "Sign AI - Signature Maker App", reviews: "50", rating: "4.6" },
      { name: "AI Signature Maker - Generator", reviews: "46", rating: "4.5" },
      { name: "Signature generator & maker", reviews: "21", rating: "4.5" },
    ],
    features: ["Generate signatures from name input", "Multiple styles: cursive, calligraphy, modern", "Customize thickness and color", "Export as transparent PNG", "AI-powered style suggestions", "Draw and save custom signatures"],
    implementation: ["SwiftUI", "PencilKit", "Core Graphics", "PNG export with transparency"],
    monetization: "Hard paywall — 1 free signature, premium for unlimited styles + export. $7.99/week or $49.99/year.",
    whyBuild: "Pop 24 with diff 15 = ratio 1.60. All competitors have fewer than 50 reviews. Diff 15 is very achievable.",
  },
  {
    rank: 28,
    name: "Foraging Guide",
    slug: "foraging-guide",
    category: "Education",
    group: "Content",
    pop: 31, diff: 21, kwScore: 10, compReviews: 50, compScore: 25, totalScore: 58,
    status: "WEAK",
    buildTime: "complex",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "forager",
    concept: "Field guide to edible wild plants, mushrooms, and berries. AI-powered camera identification, seasonal availability calendar, safe/toxic lookalike comparisons, GPS location pinning for productive foraging spots.",
    targetKeywords: ["forager", "foraging", "wild plants", "mushroom identifier", "edible plants", "wildcrafting"],
    competitors: [
      { name: "Gather: The Foraging App", reviews: "50", rating: "4.8" },
    ],
    features: ["AI-powered camera identification", "Seasonal availability calendar", "Safe/toxic lookalike comparisons", "GPS location pinning for foraging spots", "Comprehensive field guide", "Offline content database"],
    implementation: ["Vision framework", "Core ML", "MapKit", "Offline content database"],
    monetization: "Freemium — 10 free species, premium for full guide + camera ID. $7.99/week or $49.99/year.",
    whyBuild: "Pop 31 with diff 21 = ratio 1.48. Top results are VIDEO GAMES called 'Forager'. The actual foraging guide space has only 1 competitor at 50 reviews. Incredible hidden opportunity.",
  },
  {
    rank: 29,
    name: "First Aid & CPR Guide",
    slug: "first-aid-cpr",
    category: "Health & Fitness",
    group: "Content",
    pop: 31, diff: 21, kwScore: 10, compReviews: 1902, compScore: 10, totalScore: 55,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "first aid",
    concept: "Step-by-step first aid and CPR instructions with timer-guided chest compressions. Interactive scenarios, emergency contact quick-dial, offline access. Merges 'first aid' + 'resuscitation skills' keywords.",
    targetKeywords: ["first aid", "resuscitation skills", "cpr", "emergency guide", "first aid kit", "safety guide"],
    competitors: [
      { name: "First Aid: American Red Cross", reviews: "1,902", rating: "4.7" },
      { name: "First Aid - IFRC", reviews: "28", rating: "4.2" },
      { name: "FirstAid for all Emergency", reviews: "25", rating: "4.3" },
    ],
    features: ["Step-by-step CPR instructions", "Timer-guided chest compressions", "Interactive emergency scenarios", "Emergency contact quick-dial", "Offline access", "Certification prep resources"],
    implementation: ["SwiftUI", "Haptic-guided CPR rhythm", "Offline content", "Emergency dialer"],
    monetization: "Freemium — basic CPR free, premium for full first aid library + certification prep. $7.99/week or $49.99/year.",
    whyBuild: "Pop 31 with diff 21 = ratio 1.48. Red Cross app is the brand leader but it's dated and generic. Merging 'first aid' + 'resuscitation skills' keywords creates a focused CPR/emergency app.",
  },
  {
    rank: 30,
    name: "Eye Color Identifier",
    slug: "eye-color-identifier",
    category: "Lifestyle",
    group: "AI Camera",
    pop: 21, diff: 15, kwScore: 6, compReviews: 2921, compScore: 10, totalScore: 55,
    status: "MODERATE",
    buildTime: "weekend",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "eye color identifier",
    concept: "Scan your eyes with the camera, get your exact eye color name (hazel, amber, etc.), rarity percentage, and closest celebrity match. Fun, viral, shareable results.",
    targetKeywords: ["eye color identifier", "eye color", "eye scanner", "eye test", "eye analyzer"],
    competitors: [
      { name: "Eye Color Analyzer & Scanner", reviews: "291", rating: "4.7" },
      { name: "Eyepic: Eye Color Camera", reviews: "2,921", rating: "4.6" },
      { name: "Eye Color Identifier Analyzer", reviews: "31", rating: "3.9" },
    ],
    features: ["Camera-based eye color scanning", "Exact color name identification", "Rarity percentage", "Celebrity match feature", "Shareable result cards", "Color analysis history"],
    implementation: ["Vision framework", "Color analysis", "Camera macro mode"],
    monetization: "Hard paywall — 1 free scan, premium unlimited. $4.99/week or $24.99/year.",
    whyBuild: "Pop 21 with diff 15 = ratio 1.40. Eyepic dominates but diff 15 is low. Viral/fun concept with strong share mechanics.",
  },
  {
    rank: 31,
    name: "Darts Scorekeeper",
    slug: "darts-scorekeeper",
    category: "Sports",
    group: "Scorer",
    pop: 54, diff: 39, kwScore: 15, compReviews: 8156, compScore: 5, totalScore: 50,
    status: "STRONG",
    buildTime: "complex",
    pricingTier: "premium",
    pricing: { weekly: "$9.99", monthly: "$19.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "darts scorekeeper",
    concept: "Darts scoring for 501, 301, Cricket, and custom games. Checkout suggestions, stat tracking, multiplayer. Differentiate with voice scoring, Apple Watch companion, and beautiful animations.",
    targetKeywords: ["darts scorekeeper", "darts scorer", "darts app", "501 scorer", "cricket darts", "dart counter"],
    competitors: [
      { name: "Darts Scoreboard: Scorekeeper", reviews: "2,397", rating: "4.8" },
      { name: "Simple Darts Scoreboard", reviews: "8,156", rating: "4.8" },
      { name: "DartCounter", reviews: "1,790", rating: "4.8" },
      { name: "DARTS Scorekeeper 2026", reviews: "195", rating: "4.8" },
    ],
    features: ["501, 301, Cricket, and custom game modes", "Checkout suggestions", "Stat tracking and analytics", "Voice scoring ('Treble 20!')", "Apple Watch companion", "Beautiful animations and haptics"],
    implementation: ["SwiftUI", "Darts scoring rules engine", "Speech recognition", "WatchKit"],
    monetization: "Freemium — basic 501 free, premium for all game modes + stats. $9.99/week or $49.99/year.",
    whyBuild: "Pop 54 is very high. STRONG competition with multiple high-quality apps. Only worth building if you can differentiate significantly with voice scoring and Watch companion.",
  },
  {
    rank: 32,
    name: "Morse Code Translator",
    slug: "morse-code-translator",
    category: "Education",
    group: "Utility",
    pop: 26, diff: 19, kwScore: 7, compReviews: 2373, compScore: 10, totalScore: 52,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "morse code translator",
    concept: "Translate text to morse code and back. Transmit via flashlight, sound, or haptics. Include learning mode with interactive lessons, speed practice, and real-time decoding from audio input.",
    targetKeywords: ["morse code translator", "morse code", "morse decoder", "morse encoder", "sos signal"],
    competitors: [
      { name: "Morse code - Morse Master", reviews: "212", rating: "4.6" },
      { name: "Morse Code Decoder and Encoder", reviews: "18", rating: "3.6" },
      { name: "Morse Code Reader and Decoder", reviews: "2,373", rating: "4.4" },
    ],
    features: ["Text to morse code translation", "Transmit via flashlight, sound, or haptics", "Interactive learning lessons", "Speed practice mode", "Real-time audio decoding", "SOS quick send"],
    implementation: ["SwiftUI", "AVFoundation (torch + audio)", "Haptics", "Audio analysis"],
    monetization: "Freemium — basic translator free, premium for lessons + audio decode. $7.99/week or $49.99/year.",
    whyBuild: "Pop 26 with diff 19 = ratio 1.37. #3 has 2,373 reviews but diff 19 is manageable. Fun utility with education angle.",
  },
  {
    rank: 33,
    name: "Wood Identifier",
    slug: "wood-identifier",
    category: "Reference",
    group: "AI Camera",
    pop: 26, diff: 23, kwScore: 3, compReviews: 3354, compScore: 5, totalScore: 48,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "wood identifier",
    concept: "Point camera at wood grain to identify species, hardness, and best uses. Target woodworkers, furniture buyers, and lumber yard workers. Include wood hardness scale, price ranges, and project recommendations.",
    targetKeywords: ["wood identifier", "wood species", "lumber identifier", "wood scanner", "woodworking app"],
    competitors: [
      { name: "Wood Identifier: Wuddy", reviews: "208", rating: "4.7" },
      { name: "Wood Identifier: AI Scanner", reviews: "36", rating: "4.0" },
      { name: "WoodSense: Craft & Identifier", reviews: "3,354", rating: "4.6" },
    ],
    features: ["Camera-based wood species identification", "Hardness scale and properties", "Best uses and project recommendations", "Price range estimates", "Wood species database", "Offline reference guide"],
    implementation: ["Vision framework", "Core ML or Claude Vision", "Wood species database"],
    monetization: "Hard paywall — 3 free IDs, premium unlimited. $7.99/week or $49.99/year.",
    whyBuild: "Pop 26 with diff 23 = ratio 1.13. WoodSense dominates with 3,354 reviews. But diff 23 is manageable and woodworkers pay well.",
  },
  {
    rank: 34,
    name: "Mole Checker",
    slug: "mole-checker",
    category: "Medical",
    group: "AI Camera",
    pop: 24, diff: 19, kwScore: 5, compReviews: 1278, compScore: 10, totalScore: 48,
    status: "MODERATE",
    buildTime: "complex",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "mole checker",
    concept: "Track moles over time with photo comparison, ABCDE rule assessment, and change detection. NOT a diagnostic tool (disclaimer required) but a tracking/monitoring aid.",
    targetKeywords: ["mole checker", "skin cancer", "dermatology", "skin check", "mole tracker", "melanoma check"],
    competitors: [
      { name: "scanoma - mole check", reviews: "1,278", rating: "4.7" },
      { name: "AI Mole Analyzer", reviews: "0", rating: "-" },
      { name: "Al Skin Scanner", reviews: "456", rating: "4.3" },
    ],
    features: ["Photo comparison over time", "ABCDE rule assessment", "Change detection alerts", "Medical disclaimer and reminders", "Track multiple moles", "Professional skin check reminders"],
    implementation: ["Vision framework", "Photo comparison", "SwiftData", "HealthKit integration"],
    monetization: "Hard paywall — track 3 moles free, premium unlimited. $7.99/week or $49.99/year.",
    whyBuild: "Pop 24 with diff 19 = ratio 1.26. Scanoma leads with 1,278 reviews. Medical disclaimer needed. Users pay premium for health apps.",
  },
  {
    rank: 35,
    name: "Roof Pitch Calculator",
    slug: "roof-pitch-calculator",
    category: "Utilities",
    group: "Calculator",
    pop: 26, diff: 21, kwScore: 5, compReviews: 0, compScore: 35, totalScore: 47,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "roof pitch gauge",
    concept: "Measure roof pitch using your phone's accelerometer — place phone on the roof surface and get instant pitch/angle reading. Calculate materials needed based on roof dimensions.",
    targetKeywords: ["roof pitch gauge", "roof calculator", "pitch calculator", "roofing tool", "roof angle"],
    competitors: [],
    features: ["Accelerometer-based pitch measurement", "Instant angle reading", "Materials calculator (shingles, underlayment)", "Roof dimensions input", "Rafter length calculation", "Save and export estimates"],
    implementation: ["Core Motion (accelerometer)", "SwiftUI", "Material estimation formulas"],
    monetization: "Hard paywall. $7.99/week or $49.99/year.",
    whyBuild: "Pop 26 with diff 21 = ratio 1.24. Trade tools are underserved on mobile. Roofers and contractors pay well. Very little competition.",
  },
  {
    rank: 36,
    name: "Reptile Care Guide",
    slug: "reptile-care-guide",
    category: "Reference",
    group: "Content",
    pop: 25, diff: 19, kwScore: 6, compReviews: 56, compScore: 25, totalScore: 46,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "reptile",
    concept: "Care guides for snakes, lizards, turtles. Feeding schedules, habitat setup, health symptoms. Target reptile owners and enthusiasts.",
    targetKeywords: ["reptile", "reptile care", "snake care", "lizard care", "turtle care", "exotic pets"],
    competitors: [
      { name: "MorphMarket", reviews: "1,324", rating: "4.5" },
      { name: "Exotic Reptile Care", reviews: "56", rating: "4.2" },
    ],
    features: ["Comprehensive care guides per species", "Feeding schedules and reminders", "Habitat setup guides", "Health symptom checker", "Species database", "Offline access"],
    implementation: ["SwiftUI", "Content database", "Notifications for feeding schedules"],
    monetization: "Freemium — basic guides free, premium for full library. $4.99/week or $24.99/year.",
    whyBuild: "Pop 25 with diff 19 = ratio 1.32. MorphMarket is a marketplace, not a care guide. The dedicated care guide has only 56 reviews.",
  },
  {
    rank: 37,
    name: "Fly Fishing Guide",
    slug: "fly-fishing-guide",
    category: "Sports",
    group: "Content",
    pop: 25, diff: 23, kwScore: 2, compReviews: 0, compScore: 30, totalScore: 45,
    status: "MODERATE",
    buildTime: "complex",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "fly fishing",
    concept: "Fly pattern database, hatch charts, knot tutorials, river condition reports. Target the passionate fly fishing community.",
    targetKeywords: ["fly fishing", "fly patterns", "hatch chart", "fishing knots", "river conditions"],
    competitors: [],
    features: ["Fly pattern database with photos", "Hatch charts by region", "Knot tutorials with animations", "River condition reports", "Fishing log and journal", "Offline access for remote areas"],
    implementation: ["SwiftUI", "Content database", "MapKit", "Offline content"],
    monetization: "Freemium — basic content free, premium for full database. $7.99/week or $49.99/year.",
    whyBuild: "Pop 25 with diff 23 = ratio 1.09. Niche outdoor apps with moderate competition. Passionate community willing to pay.",
  },
  {
    rank: 38,
    name: "HVAC Calculator",
    slug: "hvac-calculator",
    category: "Utilities",
    group: "Calculator",
    pop: 20, diff: 19, kwScore: 1, compReviews: 0, compScore: 30, totalScore: 44,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "hvac calculator",
    concept: "BTU calculator, duct sizing, refrigerant charge, airflow calculations for HVAC techs. Professional trade tool.",
    targetKeywords: ["hvac calculator", "btu calculator", "duct sizing", "refrigerant charge", "airflow calculator"],
    competitors: [],
    features: ["BTU load calculator", "Duct sizing tool", "Refrigerant charge calculator", "Airflow calculations", "Unit conversions", "Save and export calculations"],
    implementation: ["SwiftUI", "HVAC formulas", "Unit conversion engine"],
    monetization: "Hard paywall. $7.99/week or $49.99/year.",
    whyBuild: "Pop 20 with diff 19 = ratio 1.05. Small trade tool apps. HVAC techs are high-paying professionals who need mobile tools.",
  },
  {
    rank: 39,
    name: "Volleyball Scorer",
    slug: "volleyball-scorer",
    category: "Sports",
    group: "Scorer",
    pop: 21, diff: 35, kwScore: -14, compReviews: 77, compScore: 25, totalScore: 42,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "volleyball score",
    concept: "Volleyball-specific scoreboard with rotation tracking, serve tracking, and timeout management. Dedicated tool for volleyball coaches and players.",
    targetKeywords: ["volleyball score", "volleyball scorer", "volleyball scoreboard", "volleyball app", "volleyball tracker"],
    competitors: [
      { name: "Volleyball Score Simple", reviews: "77", rating: "4.5" },
    ],
    features: ["Volleyball-specific scoreboard", "Rotation tracking", "Serve tracking", "Timeout management", "Set and match tracking", "Export game stats"],
    implementation: ["SwiftUI", "SwiftData", "Scorer engine"],
    monetization: "Freemium — basic scoring free, premium for stats and rotation. $7.99/week or $49.99/year.",
    whyBuild: "Pop 21 with diff 35 = ratio 0.60. Higher difficulty but dedicated scorer has only 77 reviews. Shared codebase with other sport scorers reduces effort.",
  },
  {
    rank: 40,
    name: "Eisenhower Matrix",
    slug: "eisenhower-matrix",
    category: "Productivity",
    group: "Specialty",
    pop: 22, diff: 35, kwScore: -13, compReviews: 1563, compScore: 10, totalScore: 40,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "eisenhower matrix",
    concept: "Simple 4-quadrant task prioritization. Urgent/Important matrix with drag-and-drop. Clean, focused productivity tool.",
    targetKeywords: ["eisenhower matrix", "priority matrix", "task prioritization", "urgent important", "todo matrix"],
    competitors: [
      { name: "Eisenhower Matrix: Todo & Task", reviews: "47", rating: "4.5" },
      { name: "Focus Matrix", reviews: "1,563", rating: "4.7" },
    ],
    features: ["4-quadrant task matrix", "Drag-and-drop task management", "Quick task entry", "Widget for home screen", "Task reminders", "Export and share matrix"],
    implementation: ["SwiftUI", "SwiftData", "Drag-and-drop", "WidgetKit"],
    monetization: "Freemium — basic matrix free, premium for widgets and export. $7.99/week or $49.99/year.",
    whyBuild: "Pop 22 with diff 35 = ratio 0.63. Focus Matrix has 1,563 reviews but the dedicated Eisenhower app has only 47. Room for a cleaner, simpler alternative.",
  },
  {
    rank: 41,
    name: "Auto Clicker",
    slug: "auto-clicker",
    category: "Utilities",
    group: "Utility",
    pop: 68, diff: 58, kwScore: 10, compReviews: 3128, compScore: 5, totalScore: 35,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "auto clicker",
    concept: "Automatic screen tapper with configurable tap intervals, multi-point sequences, and custom repeat counts. Great for accessibility, gaming, and repetitive tasks.",
    targetKeywords: ["auto clicker", "auto tapper", "automatic clicker", "screen tapper", "tap automation"],
    competitors: [
      { name: "Auto Clicker - Automatic Tap", reviews: "3,128", rating: "4.5" },
      { name: "Auto Clicker: Auto Tapper", reviews: "1,247", rating: "4.3" },
      { name: "Auto Click - Automatic Tapper", reviews: "892", rating: "4.4" },
    ],
    features: ["Configurable tap intervals", "Multi-point tap sequences", "Custom repeat counts", "Floating overlay controls", "Import/export tap configurations", "Accessibility support"],
    implementation: ["SwiftUI", "Accessibility APIs", "Timer scheduling", "Overlay UI"],
    monetization: "Hard paywall — limited free taps, premium for unlimited sequences. $7.99/week or $49.99/year.",
    whyBuild: "Pop 68 is MASSIVE — highest pop in this batch. Diff 58 is high but the sheer search volume makes it worth targeting. Leader has 3,128 reviews showing strong demand.",
  },
  {
    rank: 42,
    name: "Volume Booster",
    slug: "volume-booster",
    category: "Utilities",
    group: "Utility",
    pop: 60, diff: 49, kwScore: 11, compReviews: 443, compScore: 15, totalScore: 40,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "volume booster",
    concept: "Audio amplifier and equalizer that boosts device volume beyond system limits. Custom EQ presets, bass boost, and speaker enhancement for music, videos, and calls.",
    targetKeywords: ["volume booster", "sound booster", "bass booster", "loud speaker", "audio amplifier", "equalizer"],
    competitors: [
      { name: "Volume Booster - Loud Speaker", reviews: "443", rating: "4.2" },
      { name: "AmpMe - Speaker & Music Sync", reviews: "312", rating: "4.1" },
      { name: "Bass Booster - Volume Boost EQ", reviews: "189", rating: "4.3" },
    ],
    features: ["Volume amplification beyond system limits", "Custom EQ presets", "Bass boost mode", "Speaker enhancement", "Per-app volume control", "Widget for quick access"],
    implementation: ["AVFoundation", "Audio processing", "SwiftUI", "WidgetKit"],
    monetization: "Freemium — basic boost free, premium for EQ presets and bass boost. $4.99/week or $24.99/year.",
    whyBuild: "Pop 60 is extremely high. Diff 49 is challenging but leader only has 443 reviews — moderate competition. Music/audio tools monetize well.",
  },
  {
    rank: 43,
    name: "Elf Alert",
    slug: "elf-alert",
    category: "Entertainment",
    group: "Specialty",
    pop: 59, diff: 43, kwScore: 16, compReviews: 684, compScore: 15, totalScore: 50,
    status: "MODERATE",
    buildTime: "complex",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$19.99", trial: "7-day" },
    primaryKeyword: "elf alert",
    concept: "Seasonal Christmas app — capture photos of 'elves' in your home using AR, create Santa video calls, and generate personalized letters from the North Pole. Perfect for parents with young kids.",
    targetKeywords: ["elf alert", "santa camera", "elf on shelf", "christmas app", "santa tracker", "north pole"],
    competitors: [
      { name: "Elf Alert! Catch the Elf", reviews: "684", rating: "4.5" },
      { name: "Santa Camera: Catch Santa", reviews: "312", rating: "4.3" },
      { name: "Elf Yourself", reviews: "156", rating: "4.0" },
    ],
    features: ["AR elf placement in photos", "Santa video call generator", "Personalized North Pole letters", "Naughty/nice meter", "Elf activity tracker", "Shareable Christmas cards"],
    implementation: ["ARKit", "SwiftUI", "Camera integration", "Video generation"],
    monetization: "Freemium — 1 free photo, premium for unlimited. $4.99/week or $19.99/year. SEASONAL: peak Nov-Dec.",
    whyBuild: "Pop 59 is huge, diff 43 is manageable. SEASONAL app — build once, earn every holiday season. Leader has 684 reviews. Parents spend freely on Christmas magic for kids.",
  },
  {
    rank: 44,
    name: "Image Converter",
    slug: "image-converter",
    category: "Utilities",
    group: "Utility",
    pop: 57, diff: 48, kwScore: 9, compReviews: 137, compScore: 20, totalScore: 45,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "image converter",
    concept: "Convert images between formats — HEIC to JPG, PNG to WebP, SVG to PNG, and more. Batch processing, quality control, and resize options. Essential utility for designers and content creators.",
    targetKeywords: ["image converter", "heic to jpg", "png to jpg", "photo converter", "image format", "webp converter"],
    competitors: [
      { name: "Image Converter - Photo to PDF", reviews: "137", rating: "4.4" },
      { name: "The Image Converter", reviews: "89", rating: "4.2" },
      { name: "HEIC Converter to JPG, PNG", reviews: "42", rating: "4.1" },
    ],
    features: ["Convert between HEIC, JPG, PNG, WebP, SVG", "Batch processing", "Quality and compression control", "Resize options", "Share extension for quick access", "Drag and drop support"],
    implementation: ["SwiftUI", "Core Image", "Share Extension", "Batch processing engine"],
    monetization: "Freemium — 3 free conversions/day, premium unlimited. $4.99/week or $24.99/year.",
    whyBuild: "Pop 57 is very high. Diff 48 but leader only has 137 reviews — WEAK competition for such a high-pop keyword. Clear utility with daily use case.",
  },
  {
    rank: 45,
    name: "Light Meter",
    slug: "light-meter",
    category: "Photo & Video",
    group: "Utility",
    pop: 54, diff: 44, kwScore: 10, compReviews: 2428, compScore: 10, totalScore: 40,
    status: "MODERATE",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "light meter",
    concept: "Professional light meter using your phone's camera sensor. Measure lux, EV, foot-candles for photography, cinematography, and interior design. Includes exposure calculator and color temperature reading.",
    targetKeywords: ["light meter", "lux meter", "exposure meter", "photography light", "foot candles", "ev meter"],
    competitors: [
      { name: "myLightMeter Pro", reviews: "2,428", rating: "4.6" },
      { name: "Lux Light Meter Pro", reviews: "312", rating: "4.3" },
      { name: "Light Meter - Exposure Guide", reviews: "156", rating: "4.4" },
    ],
    features: ["Lux, EV, and foot-candle measurements", "Exposure calculator", "Color temperature reading", "Incident and reflected modes", "Measurement history and logging", "Calibration settings"],
    implementation: ["AVFoundation (camera sensor)", "Core Motion", "SwiftUI", "Measurement algorithms"],
    monetization: "Hard paywall — basic readings free, premium for advanced modes. $7.99/week or $49.99/year.",
    whyBuild: "Pop 54 is high. myLightMeter Pro leads with 2,428 reviews but it's old. Photographers and cinematographers pay premium prices for reliable tools.",
  },
  {
    rank: 46,
    name: "Tanning App",
    slug: "tanning-app",
    category: "Health & Fitness",
    group: "Specialty",
    pop: 53, diff: 43, kwScore: 10, compReviews: 10174, compScore: 5, totalScore: 35,
    status: "STRONG",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "tanning app",
    concept: "UV-aware tanning timer with skin type assessment, real-time UV index, and safe exposure recommendations. Track your tan progress with photo comparison and get alerts to flip or reapply sunscreen.",
    targetKeywords: ["tanning app", "tanning timer", "uv index", "sun exposure", "tan tracker", "sunburn timer"],
    competitors: [
      { name: "Tanify: Tanning & UV Tracker", reviews: "10,174", rating: "4.7" },
      { name: "Sun Timer - Tan & UV Tracker", reviews: "1,245", rating: "4.5" },
      { name: "My UV Index", reviews: "312", rating: "4.2" },
    ],
    features: ["UV-aware tanning timer", "Skin type assessment", "Real-time UV index", "Safe exposure calculator", "Photo progress tracking", "Flip and sunscreen alerts"],
    implementation: ["WeatherKit (UV data)", "SwiftUI", "Camera for progress photos", "Notifications"],
    monetization: "Freemium — basic timer free, premium for tracking and alerts. $7.99/week or $49.99/year.",
    whyBuild: "Pop 53 is high. STRONG competition — Tanify dominates with 10,174 reviews. Only build if you can find a unique angle like AI skin analysis or social tanning.",
  },
  {
    rank: 47,
    name: "Never Have I Ever",
    slug: "never-have-i-ever",
    category: "Entertainment",
    group: "Specialty",
    pop: 51, diff: 42, kwScore: 9, compReviews: 277, compScore: 20, totalScore: 48,
    status: "MODERATE",
    buildTime: "weekend",
    pricingTier: "entry",
    pricing: { weekly: "$4.99", monthly: "$9.99", annual: "$24.99", trial: "7-day" },
    primaryKeyword: "never have i ever",
    concept: "Party game with curated question packs — clean, spicy, couples, friends. Pass the phone or play on a shared screen. Track scores and share hilarious results.",
    targetKeywords: ["never have i ever", "party game", "drinking game", "truth or dare", "would you rather", "party questions"],
    competitors: [
      { name: "Never Have I Ever: Party Game", reviews: "277", rating: "4.5" },
      { name: "Never Have I Ever - Party", reviews: "156", rating: "4.3" },
      { name: "NHIE - Never Have I Ever Game", reviews: "89", rating: "4.1" },
    ],
    features: ["Curated question packs (clean, spicy, couples)", "Pass-the-phone mode", "Shared screen mode", "Score tracking", "Custom question creation", "Shareable results"],
    implementation: ["SwiftUI", "Content database", "Game state engine"],
    monetization: "Freemium — free starter pack, premium for all question packs. $4.99/week or $24.99/year.",
    whyBuild: "Pop 51 is strong. Weekend build — just a content app with minimal logic. Leader only has 277 reviews. Party games have viral sharing built in.",
  },
  {
    rank: 48,
    name: "Pickleball Scorer",
    slug: "pickleball-scorer",
    category: "Sports",
    group: "Scorer",
    pop: 50, diff: 41, kwScore: 9, compReviews: 19, compScore: 30, totalScore: 55,
    status: "WEAK",
    buildTime: "week",
    pricingTier: "premium",
    pricing: { weekly: "$7.99", monthly: "$14.99", annual: "$49.99", trial: "7-day" },
    primaryKeyword: "pickleball",
    concept: "Pickleball-specific scorer with singles/doubles modes, server tracking, side-out rules, and match stats. Voice scoring for hands-free court use. Shared codebase opportunity with other sport scorers.",
    targetKeywords: ["pickleball", "pickleball scorer", "pickleball score", "pickleball app", "pickleball tracker"],
    competitors: [
      { name: "Pickleball Score Counter", reviews: "19", rating: "2.9" },
      { name: "PicklePlay: Pickleball Tracker", reviews: "8", rating: "4.1" },
    ],
    features: ["Singles and doubles scoring", "Server and side tracking", "Side-out rule enforcement", "Voice scoring for hands-free use", "Match history and stats", "Apple Watch companion"],
    implementation: ["SwiftUI", "Speech recognition", "WatchKit", "SwiftData"],
    monetization: "Freemium — basic scoring free, premium for stats and voice. $7.99/week or $49.99/year.",
    whyBuild: "Pop 50 is strong. Leader has only 19 reviews with a 2.9 rating — terrible UX to beat. Pickleball is the fastest-growing sport. WEAK competition makes this a top opportunity.",
  },
];
